# Generated by Django 5.2 on 2025-04-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='fornecedores',
            new_name='fornecedor',
        ),
    ]
