# Generated by Django 5.2 on 2025-05-12 23:27

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_fornecedores_produto_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
