# Generated by Django 5.2 on 2025-05-13 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamento_options_agendamento_status_and_more'),
        ('servicos', '0005_alter_produtosservico_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicos',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico', to='servicos.servico', verbose_name='Servico'),
        ),
    ]
