# Generated by Django 5.2 on 2025-05-26 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_alter_ordemservicos_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-horario'], 'permissions': (('fechar_agendamento', 'Permite fazer o fechamento de um agendamento'),), 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
