# Generated by Django 5.2 on 2025-05-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_fornecedores_produto_fornecedor'),
        ('servicos', '0002_produtosservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(through='servicos.ProdutosServico', to='produtos.produto'),
        ),
    ]
