# Generated by Django 5.2 on 2025-05-19 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_options'),
        ('servicos', '0005_alter_produtosservico_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosservico',
            name='produto',
            field=models.ForeignKey(help_text='Nome do produto utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='produto', to='produtos.produto', verbose_name='Produto'),
        ),
    ]
